---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: centos-6.5
    driver_config:
      box: chef/centos-6.5
      customize:
        memory: 512
        cpuexecutioncap: 50

suites:
  - name: default
    run_list:
      - recipe[drupal::default]
      - recipe[drupal::backup]
    attributes: {}
    driver_config:
      network:
        - ["private_network", {ip: "192.168.33.31"}]
  - name: restore
    run_list:
      - recipe[drupal::restore]
      - recipe[drupal::_clean]
    attributes: {}
    driver_config:
      network:
        - ["private_network", {ip: "192.168.33.32"}]
  - name: backup
    run_list:
      - recipe[drupal::restore]
      - recipe[drupal::_clean]
      - recipe[drupal::backup]
    attributes: {}
    driver_config:
      network:
        - ["private_network", {ip: "192.168.33.33"}]
