---
driver_plugin: digitalocean
driver_config:
  digitalocean_client_id: <%= ENV['DIGITALOCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITALOCEAN_API_KEY'] %>
  ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
  ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver_plugin: digitalocean
    driver_config:
      image_id: 6372108

suites:
  - name: default
    run_list:
      - recipe[drupal::default]
      - recipe[drupal::_backup_script]
      - recipe[drupal::_https]
      - recipe[drupal::backup]
    data_bags_path: test/integration/default/data_bags
    encrypted_data_bag_secret_key_path: test/integration/default/data_bag_key
    attributes: {}
  - name: restore
    run_list:
      - recipe[drupal::restore]
      - recipe[drupal::_clean]
      - recipe[drupal::_https]
    data_bags_path: test/integration/default/data_bags
    encrypted_data_bag_secret_key_path: test/integration/default/data_bag_key
    attributes: {}
  - name: backup
    run_list:
      #- recipe[drupal::restore]
      #- recipe[drupal::_clean]
      - recipe[drupal::backup]
    data_bags_path: test/integration/default/data_bags
    encrypted_data_bag_secret_key_path: test/integration/default/data_bag_key
    attributes: {}
